## Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [2]:
from numpy import sqrt
import numpy as np
def distance(x1, y1, x2, y2):
    result = sqrt((x1 - x2)**2 + (y1 - y2)**2)
    return result

print(distance(1, 1, 4, 4))

4.242640687119285


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [ ]:
s = ""
def season(month):
    global s
    if month >= 1 and month < 3 or month == 12:
        s = "winter"
    elif month >= 3 and month < 6:
        s = "spring"
    elif month >= 6 and month < 9:
        s = "summer"
    else:
        s = "autumn"

print(s)
season(5)
print(s)


winter


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [27]:
def is_prime(n):
    for i in range(2, int(np.ceil(sqrt(n)))):
        if (n % i == 0):
            return False
    return True    

print (is_prime(24))

False


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [32]:
def reverse_list(lst):
    result = []
    for i in range (counter(lst), 0, -1):
        result.append(lst[i - 1])
    return result

def counter(lst):
    result = 0
    for item in lst:
        result += 1
    return result

print(reverse_list([8, 1, 0, 4]))

[4, 0, 1, 8]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [35]:
phrase = "Привет мир!"
start = 4
end = 8
result = []
for i in range(start - 1, end):
    result.append(phrase[i].upper())

print (result)

['В', 'Е', 'Т', ' ', 'М']


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [36]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
for i in range (1, int(len(x) / 2), 2):
    temp = x[i]
    x[i] = x[len(x) - i]
    x[len(x) - i] = temp

print(x)

[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [37]:
for i in range(0, 500, 7):
    div10 = int(i / 10)
    div100 = int(div10 / 10)
    if (i > 10 and i < 100):
        if(i % 10 == 8 or div10 % 10 == 8):
            print(i)
    elif(i > 100):
        if(i % 10 == 8 or div10 % 10 == 8 or div100 % 10 == 8):
            print(i)


28
84
98
168
182
189
238
280
287
308
378
385
448
483


**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [1]:
def more_than_five(lst):
    result = []
    for i in range(0, len(lst)):
        if (abs(lst[i]) > 10):
            result.append(lst[i])
    
    return result

print(more_than_five([1, 2, 3, 4, 5, 6, 7, 8, 9, -11, 10, 11, 1, 2, 3, 22]))

[-11, 11, 22]


# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [9]:
length = 10
matrix = np.zeros((length, length))
for i in range(0, length):
    matrix[0, i] = 1
    matrix[i, 0] = 1
    matrix[length - 1, i] = 1
    matrix[i, length - 1] = 1

print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [11]:
length = 5
matrix = np.zeros((length, length))
for i in range(1, length):
    matrix[i - 1, i] = i

print(matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [24]:
length = 5
matrix = np.random.randint(20, size=(length, length))
print(matrix)
for i in range(0, matrix.shape[0]):
    mean = int(np.mean(matrix[i, :]))
    print(mean)
    matrix[i, :] -= mean

print(matrix)

[[ 8 14 13 12 12]
 [ 3 10 12 15  5]
 [15 17 15  7  6]
 [ 8  7  3 10 13]
 [16  4  3  5 11]]
11
9
12
8
7
[[-3  3  2  1  1]
 [-6  1  3  6 -4]
 [ 3  5  3 -5 -6]
 [ 0 -1 -5  2  5]
 [ 9 -3 -4 -2  4]]


**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [29]:
def signChange(array):
    array[np.logical_and(array > 3, array < 8)] *= -1
    return array

print(signChange(np.array([[3, 8, 5, 2, 1, 7], [5, 2, 22, 6, 4, 7]], int)))

[[ 3  8 -5  2  1 -7]
 [-5  2 22 -6 -4 -7]]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

In [31]:
def subtractMean(array):
    for i in range(0, array.shape[0]):
        mean = int(np.mean(array[i, :]))
        print(mean)
        array[i, :] -= mean
    return array

print(subtractMean(np.array([[3, 8, 5, 2, 1, 7], [5, 2, 22, 6, 4, 7]], int)))

4
7
[[-1  4  1 -2 -3  3]
 [-2 -5 15 -1 -3  0]]


**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [37]:
vector = np.array([1, 2, 3, 4, 5], int)
result = np.array([], int)
for i in range(0, vector.shape[0]):
    if (i < vector.shape[0] - 1):
        result = np.append(result, [vector[i], 0, 0, 0])
    else:
        result = np.append(result, [vector[i]])

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [61]:
from random import randint

def changeRowsRand(matrix):
    row1 = randint(0, matrix.shape[0] - 1)
    row2 = randint(0, matrix.shape[0] - 1)
    temp = np.copy(matrix[row1, :])
    matrix[row1, :] = matrix[row2, :]
    matrix[row2, :] = temp
    return matrix

print(changeRowsRand(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], int)))

[[ 1  2  3]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [64]:
def mostFrequent(array):
    bins = np.bincount(array)
    return np.argmax(bins)

print(mostFrequent([1, 5, 20, 4, 2, 2, 7, 7, 3, 7, 5, 6]))

7


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [71]:
step = 4

def calcQuad(array):
    sums = []
    for i in range(0, array.shape[0], step):
        for k in range(0, array.shape[1], step):
            sums.append(np.sum(array[i:(i + step), k:(k + step)]))
    return sums

print(calcQuad(np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16],
                         [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                         [5, 4, 2, 8, 10, 6, 7, 23, 9, 10, 11, 2, 13, 14, 5, 16]], int)))

[58, 144, 148, 212, 58, 144, 148, 212, 58, 144, 148, 212, 58, 144, 148, 212]


**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [3]:
array = np.array([[1, 2, 6], [2, 8, 3]], int)

def biggestNumbers(n):
    temp = np.reshape(array, (array.shape[0] * array.shape[1]))

    if n >= temp.shape[0]:
        return None

    temp = np.sort(temp)
    result = []
    for i in range(temp.shape[0] - 1, temp.shape[0] - 1 - n, -1):
        result.append(temp[i])
    return result

n = (int)(input("Введите желаемое число наибольших значений массива: "))
print(str(n) + " наибольших чисел массива: ")
print(biggestNumbers(n))

5 наибольших чисел массива: 
[8, 6, 3, 2, 2]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [5]:
def findRows(matrix):
    result = []
    for i in range(0, matrix.shape[0]):
        if matrix[i, 0] != np.mean(matrix[i, :]):
            result.append(matrix[i, :])
    return result

print(findRows(np.array([[1, 1, 1], [2, 3, 2], [4, 4, 4], [5, 5, 5], [6, 1, 2], [0, -1, 2]], int)))

[array([2, 3, 2]), array([6, 1, 2]), array([ 0, -1,  2])]


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [8]:
def filter(array):
    return np.unique(array, axis=0)

print(filter(np.array([[7, 2, 3, 1], [1, 2, 3, 4], [2, 5, 3, 1], [1, 2, 3, 4], [7, 2, 3, 1]], int)))

[[1 2 3 4]
 [2 5 3 1]
 [7 2 3 1]]


**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [10]:
def distance(vec1, vec2):
    result = 0
    for i in range(0, vec1.shape[0]):
        result += (vec1[i] - vec2[i])**2
    result = np.sqrt(result)
    return result

print(distance(np.array([1, 2, 3], float), np.array([2, 2, 3], float)))

1.0


**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [12]:
def cos(vec1, vec2):
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

print(cos(np.array([3, -4, 0], float), np.array([4, -4, -2], float)))

0.9333333333333333


**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


In [14]:
def round(vec):
    result = []
    for i in range(0, vec.shape[0]):
        if vec[i] >= 0:
            result.append(np.ceil(vec[i]))
        else:
            result.append(np.floor(vec[i]))
    return result

print(round(np.array([-0.2, 0.1, 0], float)))

[-1.0, 1.0, 0.0]


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

In [19]:
Z = []

def sortNums(A, B):
    global Z
    Z = np.intersect1d(A, B)

sortNums(np.array([4, 1, 5, 2], int), np.array([1, 4, 3, 1], int))
print(Z)

[1 4]


**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [21]:
def max(vec):
    temp = np.array([], int)
    for i in range(1, vec.shape[0]):
        if vec[i - 1] == 0:
            temp = np.append(temp, vec[i])
    return temp[np.argmax(temp)]

print(max(np.array([6, 2, 0, 3, 0, 0, 5, 7, 0], int)))

5


**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [22]:
def biggestLength(matrix): 
    length = 0
    index = -1
    for i in range(0, matrix.shape[0]):
        lngth = np.linalg.norm(matrix[i, :])
        if lngth > length:
            length = lngth
            index = i
    return (matrix[index, :], length)

print(biggestLength(np.array([[1, 3, 5], [2, 8, 7], [3, 5, 9]], float)))

(array([2., 8., 7.]), 10.816653826391969)
